### ISSUE TITLE
ProfanityFilter in ReinfyTeam

### ISSUE THREAD

**Issue by xqwtxon** [ReinfyTeam/ProfanityFilter#1]
### Move the Project.
[**@xqwtxon/ProfanityFilter**](https://github.com/xqwtxon/ProfanityFilter) is planned to deleted in github.<br>The project has been moved up to [**@ReinfyTeam/ProfanityFilter**](https://github.com/ReinfyTeam/ProfanityFilter)

<hr>

*As of that will no longer maintained the original repository.*

**Comment by Reinfy** [comment]
**As of Wed, Jul 13 at 7:16, Your plugin had been submitted to the poggit.**

##### Do not reply in this message. This is auto-generated message.

**Comment by xqwtxon** [comment]
**Cannot be deleted!**

*It will archived until this plugin would be next in future.*
