### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by Reinfy** [ReinfyTeam/ProfanityFilter#15]
**Add more languages...**
The way people understand their own language.

**Comment by xqwtxon** [comment]
Ok, i will add Filipino languages because i only know my own language.

**Comment by xqwtxon** [comment]
I added Filipino Language (Phillipines)

**Comment by xqwtxon** [comment]
Updated all languages in `v0.0.8`

**Comment by xRodzMC** [comment]
Removed outdated languages in `v0.1.1`

### Outdated Languages
- German Translation by @SayakaPM [`resources/languages/deu.yml`](https://github.com/ReinfyTeam/ProfanityFilter/commit/8e45a926b5d897610526bc733858b98cc3a1d2cc#diff-88168abd650820b63600f1ea89345e4848de70f420a09cee9a30e0a45d67c754)
- Filipino Translation by @xqwtxon [`resources/languages/fil.yml`](https://github.com/ReinfyTeam/ProfanityFilter/commit/8e45a926b5d897610526bc733858b98cc3a1d2cc#diff-2c08a21fbd73c85f387bd4e7eec0cfdee89fabcd2f0ac66a78ce395b0dd19e58)
- Vietnamese Translation by @NhanAZ [`resources/languages/vie.yml`](https://github.com/ReinfyTeam/ProfanityFilter/commit/8e45a926b5d897610526bc733858b98cc3a1d2cc#diff-37576d372c367beb566c6c32ccdbc3160b56c72f4209785605022964e5c6927f)

**Comment by NhanAZ** [comment]
Added Vietnamese

**Comment by xRodzMC** [comment]
Closing this **as** _you can now access localizations files at_ [**here**](https://gitlocalize.com/repo/8866)

_**For more information about creating language files, please see**_ [**wiki**](https://github.com/ReinfyTeam/ProfanityFilter/wiki)
